pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t deansohn/go-example-webserver:$DRONE_COMMIT_SHA .
        --label org.label-schema.vcs-ref=$DRONE_COMMIT_SHA
        --label build-number=$DRONE_BUILD_NUMBER
        --label build-date="$(date)"
        -t deansohn/go-example-webserver:$DRONE_COMMIT_SHA .
  test:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run deansohn/go-example-webserver:$DRONE_COMMIT_SHA /test.sh
  push:
    image: docker
    environment:
      - PASS=${HUB_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login -u deansohn -p $PASS
      - docker push deansohn/go-example-webserver:$DRONE_COMMIT_SHA
  deploy:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker pull deansohn/go-example-webserver:$DRONE_COMMIT_SHA
      - docker tag deansohn/go-example-webserver:$DRONE_COMMIT_SHA deansohn/go-example-webserver:production
      - docker stack deploy -c ./docker-compose.yml go-example-webserver
